const API_URL="https://wiener-ia.onrender.com";
const messages=document.getElementById("messages"),userInput=document.getElementById("userInput"),sendBtn=document.getElementById("sendBtn"),newChatBtn=document.getElementById("newChatBtn"),historyList=document.getElementById("historyList"),clearHistoryBtn=document.getElementById("clearHistoryBtn");
let history=[],currentMode="chat",lastCausalState=null,memoryCount=0,currentConversationId=null,isSending=false,activeController=null;
const HISTORY_KEY="wiener_ia_navigation_history_v2";
const MODES={chat:"Envoyez un message à Wiener IA...",exercise:"Posez votre exercice...",search:"Rechercher sur le Web...",image:"Décrivez l’image à générer...",pdf:"Posez une question sur votre document...",calculator:"Entrez un calcul..."};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function scrollChat(force=false){const c=$("#chatContainer");if(!c)return;const near=c.scrollHeight-c.scrollTop-c.clientHeight<180;if(force||near)c.scrollTo({top:c.scrollHeight,behavior:"auto"});}
function escapeHTML(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));}
function renderMarkdown(text){let s=escapeHTML(text).replace(/```([\w+-]*)\n?([\s\S]*?)```/g,(_,lang,code)=>`<pre class="code-block"><code data-language="${escapeHTML(lang)}">${code}</code></pre>`);s=s.replace(/`([^`\n]+)`/g,"<code>$1</code>").replace(/\*\*(.+?)\*\*/g,"<strong>$1</strong>").replace(/\*(.+?)\*/g,"<em>$1</em>").replace(/(^|\n)### (.+)/g,"$1<h4>$2</h4>").replace(/(^|\n)## (.+)/g,"$1<h3>$2</h3>").replace(/(^|\n)# (.+)/g,"$1<h2>$2</h2>");s=s.replace(/(^|\n)[-•] (.+)/g,"$1<li>$2</li>");s=s.replace(/(<li>[^]*?<\/li>)(?=<br><li>|$)/g,"<ul>$1</ul>");s=s.replace(/\bhttps?:\/\/[^\s<]+/g,u=>`<a href="${u}" target="_blank" rel="noopener noreferrer">${u}</a>`);return s.replace(/\n/g,"<br>");}
function addActions(div,content){if(div.dataset.role!=="assistant")return;const actions=document.createElement("div");actions.className="wiener-message-actions";const copy=document.createElement("button");copy.type="button";copy.className="wiener-copy-btn";copy.setAttribute("aria-label","Copier la réponse");copy.title="Copier";copy.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="9" y="9" width="11" height="11" rx="2"></rect><path d="M6 15H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v1"></path></svg>';copy.addEventListener("click",async()=>{try{await navigator.clipboard.writeText(String(content??""));copy.classList.add("is-copied");copy.textContent="✓";setTimeout(()=>{copy.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="9" y="9" width="11" height="11" rx="2"></rect><path d="M6 15H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v1"></path></svg>';copy.classList.remove("is-copied")},1200)}catch(_){}});actions.appendChild(copy);div.appendChild(actions);}
function addMessage(content,role){const div=document.createElement("div"),isUser=role==="user";div.className=isUser?"message user":"message assistant";div.dataset.role=isUser?"user":"assistant";const label=document.createElement("div");label.className="message-label";label.textContent=isUser?"Vous":"Wiener IA";const body=document.createElement("div");body.className="message-content";if(isUser)body.textContent=String(content??"");else body.innerHTML=renderMarkdown(content);div.append(label,body);messages?.appendChild(div);if(!isUser)addActions(div,content);scrollChat();return div;}
async function typeMessage(content,role="assistant",speed=2){const div=document.createElement("div"),isUser=role==="user";div.className=isUser?"message user":"message assistant";div.dataset.role=isUser?"user":"assistant";const label=document.createElement("div");label.className="message-label";label.textContent=isUser?"Vous":"Wiener IA";const body=document.createElement("div");body.className="message-content";div.append(label,body);messages?.appendChild(div);const text=String(content??"");if(!text){scrollChat(true);return div;}if(text.length>1400){body.innerHTML=renderMarkdown(text);addActions(div,text);scrollChat(true);return div;}for(let i=0;i<text.length;i++){body.textContent+=text[i];if(i%10===0)scrollChat();if(speed>0)await new Promise(r=>setTimeout(r,speed));}body.innerHTML=renderMarkdown(text);addActions(div,text);scrollChat(true);return div;}
function addImageMessage(dataUrl){const div=document.createElement("div");div.className="message assistant";div.dataset.role="assistant";const img=document.createElement("img");img.src=dataUrl;img.alt="Image générée par Wiener IA";img.className="generated-image";div.appendChild(img);messages?.appendChild(div);scrollChat(true);}
function showSearchSources(sources){if(!Array.isArray(sources)||!sources.length||!messages)return;const wrap=document.createElement("div");wrap.className="message assistant search-sources";wrap.dataset.role="assistant";const title=document.createElement("div");title.className="sources-title";title.textContent="Sources utilisées";wrap.appendChild(title);const list=document.createElement("div");sources.slice(0,8).forEach((source,i)=>{if(!source?.uri)return;try{const u=new URL(source.uri);if(!/^https?:$/.test(u.protocol))return;const link=document.createElement("a");link.href=u.href;link.target="_blank";link.rel="noopener noreferrer";link.textContent=`${i+1}. ${source.title||u.hostname}`;list.appendChild(link)}catch(_){}});wrap.appendChild(list);messages.appendChild(wrap);scrollChat(true);}
function loadNavigationHistory(){try{const raw=localStorage.getItem(HISTORY_KEY)||localStorage.getItem("wiener_ia_navigation_history_v1");const items=raw?JSON.parse(raw):[];return Array.isArray(items)?items:[]}catch(_){return[]}}
function saveNavigationHistory(items){try{localStorage.setItem(HISTORY_KEY,JSON.stringify(items.slice(0,50)))}catch(_){}}
function renderNavigationHistory(filter=""){if(!historyList)return;const items=loadNavigationHistory().filter(x=>!x.archived);historyList.innerHTML="";const q=String(filter||"").toLowerCase().trim();const visible=items.filter(x=>!q||String(x.title||"").toLowerCase().includes(q)||JSON.stringify(x.history||[]).toLowerCase().includes(q));if(!visible.length){historyList.innerHTML='<div class="history-empty">Aucune conversation</div>';return}visible.forEach(item=>{const button=document.createElement("button");button.type="button";button.className="history-item"+(item.id===currentConversationId?" current":"");button.dataset.id=item.id;const title=document.createElement("span");title.className="history-title";title.textContent=item.title||"Nouvelle conversation";const date=document.createElement("small");date.textContent=new Date(item.updatedAt||Date.now()).toLocaleDateString("fr-FR");const actions=document.createElement("span");actions.className="history-actions";const rename=document.createElement("span");rename.className="history-action";rename.textContent="✎";rename.title="Renommer";rename.setAttribute("role","button");const remove=document.createElement("span");remove.className="history-action";remove.textContent="×";remove.title="Supprimer";remove.setAttribute("role","button");actions.append(rename,remove);button.append(title,date,actions);button.addEventListener("click",e=>{if(e.target===rename||e.target===remove)return;restoreConversation(item.id);closeSidebar()});rename.addEventListener("click",e=>{e.stopPropagation();renameConversation(item.id)});remove.addEventListener("click",e=>{e.stopPropagation();deleteConversation(item.id)});historyList.appendChild(button)})}
function saveCurrentConversation(){const visible=[...messages.querySelectorAll(".message")].map(m=>({role:m.dataset.role||"assistant",content:m.querySelector(".message-content")?.textContent||m.textContent||""})).filter(x=>x.content.trim());const first=visible.find(x=>x.role==="user");if(!first)return;const items=loadNavigationHistory(),id=currentConversationId||String(Date.now());currentConversationId=id;const item={id,title:first.content.replace(/\s+/g," ").trim().slice(0,55)+(first.content.length>55?"…":""),updatedAt:new Date().toISOString(),history,mode:currentMode,archived:false};const existing=items.find(x=>x.id===id);if(existing)Object.assign(existing,item);else items.unshift(item);saveNavigationHistory(items);renderNavigationHistory();}
function restoreConversation(id){const item=loadNavigationHistory().find(x=>x.id===id);if(!item||!messages)return;currentConversationId=item.id;history=Array.isArray(item.history)?item.history:[];currentMode=item.mode||"chat";messages.innerHTML="";history.forEach(m=>addMessage(m.content,m.role==="model"?"assistant":m.role));updateModeUI();scrollChat(true);userInput?.focus()}
function renameConversation(id){const items=loadNavigationHistory(),item=items.find(x=>x.id===id);if(!item)return;const title=window.prompt("Nouveau nom de la conversation",item.title||"");if(title?.trim()){item.title=title.trim().slice(0,100);item.updatedAt=new Date().toISOString();saveNavigationHistory(items);renderNavigationHistory()}}
function deleteConversation(id){if(!window.confirm("Supprimer cette conversation ?"))return;const items=loadNavigationHistory().filter(x=>x.id!==id);saveNavigationHistory(items);if(currentConversationId===id)startNewConversation(false);else renderNavigationHistory()}
function clearHistory(){if(!window.confirm("Effacer tout l’historique ?"))return;localStorage.removeItem(HISTORY_KEY);localStorage.removeItem("wiener_ia_navigation_history_v1");currentConversationId=null;renderNavigationHistory()}
function setBusy(value){isSending=Boolean(value);if(sendBtn){sendBtn.disabled=isSending||!(userInput?.value.trim()||window.wienerSelectedFile);sendBtn.setAttribute("aria-busy",String(isSending));sendBtn.classList.toggle("is-loading",isSending)}if(userInput)userInput.disabled=isSending}
function autoResize(){if(!userInput)return;userInput.style.height="auto";const max=180;userInput.style.height=Math.min(userInput.scrollHeight,max)+"px";userInput.style.overflowY=userInput.scrollHeight>max?"auto":"hidden";updateSendState()}
function updateSendState(){if(sendBtn&&!isSending)sendBtn.disabled=!(userInput?.value.trim()||window.wienerSelectedFile)}
function updateModeUI(){document.querySelectorAll(".plus-menu button[data-mode]").forEach(b=>{const active=(b.dataset.mode||"chat")===currentMode;b.classList.toggle("active",active);b.setAttribute("aria-pressed",String(active))});if(userInput&&!window.wienerSelectedFile)userInput.placeholder=MODES[currentMode]||MODES.chat}
function setMode(mode){currentMode=MODES[mode]?mode:"chat";updateModeUI();closePlusMenu();userInput?.focus()}
function toggleMode(mode){setMode(mode||"chat")}
function closePlusMenu(){const menu=$("#plusMenu"),btn=$("#plusBtn");if(menu){menu.hidden=true;btn?.setAttribute("aria-expanded","false")}}
function openPlusMenu(){const menu=$("#plusMenu"),btn=$("#plusBtn");if(menu){menu.hidden=false;btn?.setAttribute("aria-expanded","true")}}
function closeSidebar(){const sidebar=$("#sidebar"),btn=$("#mobileMenuBtn"),overlay=$("#sidebarOverlay");sidebar?.classList.remove("mobile-open");overlay?.classList.remove("is-visible");btn?.setAttribute("aria-expanded","false");btn?.setAttribute("aria-label","Ouvrir le menu")}
function openSidebar(){const sidebar=$("#sidebar"),btn=$("#mobileMenuBtn"),overlay=$("#sidebarOverlay");sidebar?.classList.add("mobile-open");overlay?.classList.add("is-visible");btn?.setAttribute("aria-expanded","true");btn?.setAttribute("aria-label","Fermer le menu")}
function removeSelectedFile(){const input=$("#fileInput"),preview=$("#filePreview");if(input)input.value="";window.wienerSelectedFile=null;if(preview)preview.hidden=true;updateModeUI();updateSendState()}
function formatFileSize(bytes){if(bytes<1024)return `${bytes} octets`;if(bytes<1048576)return `${(bytes/1024).toFixed(1)} KB`;return `${(bytes/1048576).toFixed(1)} MB`}
function handleFile(file){if(!file)return;const allowed=["application/pdf","image/png","image/jpeg","image/webp"];if(!allowed.includes(file.type)){addMessage("Type de fichier non pris en charge. Utilise un PDF, PNG, JPEG ou WebP.","assistant");return}if(file.size>20*1024*1024){addMessage("Fichier trop volumineux. Taille maximale : 20 MB.","assistant");return}window.wienerSelectedFile=file;const preview=$("#filePreview");if(preview)preview.hidden=false;$("#fileName")?.replaceChildren(document.createTextNode(file.name));$("#fileSize")?.replaceChildren(document.createTextNode(formatFileSize(file.size)));$("#fileIcon")?.replaceChildren(document.createTextNode(file.type==="application/pdf"?"📄":"🖼️"));if(userInput)userInput.placeholder="Que voulez-vous savoir sur ce fichier ?";closePlusMenu();updateSendState();userInput?.focus()}
function showLoading(mode){const div=document.createElement("div");div.className="message assistant loading-message";div.dataset.role="assistant";const label=document.createElement("div");label.className="message-label";label.textContent="Wiener IA";const body=document.createElement("div");body.className="message-content typing-dots";body.setAttribute("aria-live","polite");body.setAttribute("aria-label",mode==="search"?"Recherche Web en cours":mode==="file"?"Analyse du fichier en cours":"Wiener IA réfléchit");body.innerHTML=mode==="search"?'<span class="loading-label">Recherche Web</span><span>·</span><span>·</span><span>·</span>':mode==="file"?'<span class="loading-label">Analyse du fichier</span><span>·</span><span>·</span><span>·</span>':'<span class="loading-label">Réflexion</span><span>·</span><span>·</span><span>·</span>';div.append(label,body);messages.appendChild(div);scrollChat(true);return div}
async function requestJSON(url,options={},retries=2){let lastError=null;for(let attempt=0;attempt<=retries;attempt++){const controller=new AbortController();activeController=controller;const timeout=setTimeout(()=>controller.abort(),30000);try{if(!navigator.onLine)throw Object.assign(new Error("Connexion Internet indisponible."),{offline:true});const response=await fetch(url,{...options,cache:"no-store",signal:controller.signal});const data=await response.json().catch(()=>({}));if(response.ok)return data;const err=new Error(data.error||`Erreur HTTP ${response.status}`);err.status=response.status;if([408,425,429,500,502,503,504].includes(response.status)&&attempt<retries){await new Promise(r=>setTimeout(r,500*(attempt+1)));continue}throw err}catch(error){lastError=error;if(error.name==="AbortError")lastError=Object.assign(new Error("Le serveur met trop de temps à répondre."),{timeout:true});if((!lastError.status||[408,425,429,500,502,503,504].includes(lastError.status))&&attempt<retries){await new Promise(r=>setTimeout(r,500*(attempt+1)));continue}throw lastError}finally{clearTimeout(timeout)}}throw lastError||new Error("Serveur Wiener IA inaccessible.")}
async function sendFile(file,prompt){const form=new FormData();form.append("file",file,file.name);form.append("prompt",prompt||"Analyse ce fichier et réponds à ma question.");return requestJSON(API_URL+"/api/analyze-file",{method:"POST",body:form},2)}
async function sendImage(prompt){const data=await requestJSON(API_URL+"/api/image",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt})},2);if(data.image)addImageMessage(data.image);return data}
async function sendMessage(){if(isSending||!userInput||!messages)return;const text=userInput.value.trim(),selectedFile=window.wienerSelectedFile||null;if(!text&&!selectedFile)return;if(text)addMessage(text,"user");userInput.value="";autoResize();const mode=selectedFile?"file":currentMode,loading=showLoading(mode);setBusy(true);try{let data,answer,shouldAdd=false;if(selectedFile){data=await sendFile(selectedFile,text);answer=data.answer;removeSelectedFile()}else if(currentMode==="image"){data=await sendImage(text);answer=data.answer||(!data.image?"Le modèle image n’a pas retourné d’image.":"")}else{let endpoint="/api/chat",body;if(currentMode==="exercise"){endpoint="/api/exercises";body={question:text,level:"Non précisé",subject:"Non précisée"}}else if(currentMode==="search"){endpoint="/api/search";body={query:text}}else if(currentMode==="calculator"){endpoint="/api/calculate";body={expression:text}}else if(currentMode==="pdf"){endpoint="/api/analyze";body={text}}else{shouldAdd=true;history.push({role:"user",content:text});body={messages:history}}data=await requestJSON(API_URL+endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)},2);answer=data.answer??data.result??data.response??data.analysis??data.text??data.message;if(shouldAdd&&answer!==undefined)history.push({role:"assistant",content:String(answer)});if(Number.isFinite(Number(data.memoryCount)))memoryCount=Number(data.memoryCount);lastCausalState=data.causal||null}loading.remove();if(answer!==undefined&&answer!==null&&String(answer).trim()!=="")await typeMessage(answer,"assistant",2);if(currentMode==="search"&&Array.isArray(data.sources))showSearchSources(data.sources);saveCurrentConversation()}catch(error){loading.remove();const textError=error.offline?"Connexion Internet indisponible.":error.timeout?"Le serveur met trop de temps à répondre.":error.status===429?"Le service est temporairement limité. Réessayez dans quelques instants.":error.status===503?"Le service Wiener IA est temporairement indisponible.":(error.message||"Serveur Wiener IA inaccessible.");const div=addMessage("❌ "+textError,"assistant");const retry=document.createElement("button");retry.type="button";retry.className="retry-btn";retry.textContent="Réessayer";retry.addEventListener("click",()=>{div.remove();userInput.value=text;autoResize();sendMessage()});div.appendChild(retry);console.error("Wiener IA:",error)}finally{activeController=null;setBusy(false);userInput.disabled=false;autoResize();userInput.focus()}}
function startNewConversation(focus=true){history=[];lastCausalState=null;currentConversationId=null;setMode("chat");if(messages)messages.innerHTML='<div class="message assistant" data-role="assistant"><div class="message-content">👋 Bonjour !<br><br>Je suis <strong>Wiener IA</strong>.<br><br>Comment puis-je vous aider aujourd’hui ?</div></div>';removeSelectedFile();if(userInput){userInput.value="";autoResize();if(focus)userInput.focus()}renderNavigationHistory();closeSidebar()}
async function analyzeFunctionally(text){const value=String(text||"").trim();if(!value)return null;return requestJSON(API_URL+"/api/consciousness",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:value})},2)}
async function getCausalState(){return requestJSON(API_URL+"/api/causal/state",{},1)}
async function getMemory(){const data=await requestJSON(API_URL+"/api/memory",{},1);memoryCount=Number(data.count||0);return data}
async function remember(content,role="user"){const value=String(content||"").trim();if(!value)return null;const data=await requestJSON(API_URL+"/api/memory",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({content:value,role})},1);memoryCount=Number(data.count||memoryCount);return data}
async function clearMemory(){const data=await requestJSON(API_URL+"/api/memory",{method:"DELETE"},1);memoryCount=0;return data}
async function checkServer(){try{const data=await requestJSON(API_URL+"/api/health",{},1);memoryCount=Number(data.memoryCount||0);document.body.dataset.backend="online";return data.ok===true}catch(_){document.body.dataset.backend="offline";return false}}
function installUI(){let overlay=$("#sidebarOverlay");if(!overlay){overlay=document.createElement("div");overlay.id="sidebarOverlay";document.body.appendChild(overlay)}const plusBtn=$("#plusBtn"),plusMenu=$("#plusMenu"),mobileBtn=$("#mobileMenuBtn"),sidebar=$("#sidebar"),fileInput=$("#fileInput"),removeBtn=$("#removeFileBtn");const guard=(selector,fn)=>document.addEventListener("click",e=>{const target=e.target.closest?.(selector);if(target){e.preventDefault();e.stopImmediatePropagation();fn(target,e)}},true);guard("#plusBtn",()=>plusMenu?.hidden?openPlusMenu():closePlusMenu());guard("#mobileMenuBtn",()=>sidebar?.classList.contains("mobile-open")?closeSidebar():openSidebar());guard("#newChatBtn",()=>startNewConversation());guard("#clearHistoryBtn",clearHistory);guard("#plusFileBtn",()=>fileInput?.click());guard("#removeFileBtn",removeSelectedFile);document.addEventListener("change",e=>{if(e.target===fileInput){e.stopImmediatePropagation();handleFile(fileInput.files?.[0])}},true);document.addEventListener("click",e=>{if(sidebar?.classList.contains("mobile-open")&&!sidebar.contains(e.target)&&e.target!==mobileBtn)closeSidebar();if(plusMenu&&!plusMenu.hidden&&!plusMenu.contains(e.target)&&e.target!==plusBtn)closePlusMenu()});document.addEventListener("keydown",e=>{if(e.key==="Escape"){closePlusMenu();closeSidebar();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();startNewConversation()}});overlay.addEventListener("click",closeSidebar);$$(".plus-menu button[data-mode]").forEach(btn=>btn.addEventListener("click",()=>setMode(btn.dataset.mode||"chat")));dropSetup();userInput?.addEventListener("input",autoResize);userInput?.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();if(!isSending)sendMessage()}});sendBtn?.addEventListener("click",sendMessage);const search=document.createElement("input");search.className="history-search";search.type="search";search.placeholder="Rechercher dans l’historique";search.setAttribute("aria-label","Rechercher dans l’historique");$(".history-head")?.insertAdjacentElement("afterend",search);search.addEventListener("input",()=>renderNavigationHistory(search.value));window.addEventListener("online",()=>{document.body.dataset.network="online";checkServer()});window.addEventListener("offline",()=>{document.body.dataset.network="offline"});window.addEventListener("resize",()=>{if(window.innerWidth>900)closeSidebar();autoResize()});const splash=$("#wienerSplash");requestAnimationFrame(()=>splash?.classList.add("is-hidden"))}
function dropSetup(){const zone=$(".input-container"),input=$("#fileInput");if(!zone)return;["dragenter","dragover"].forEach(t=>zone.addEventListener(t,e=>{e.preventDefault();zone.classList.add("drag-over")}));["dragleave","drop"].forEach(t=>zone.addEventListener(t,e=>{e.preventDefault();zone.classList.remove("drag-over")}));zone.addEventListener("drop",e=>handleFile(e.dataTransfer?.files?.[0]));}
installUI();renderNavigationHistory();updateModeUI();autoResize();checkServer();
window.WienerIA={sendMessage,checkServer,analyzeFunctionally,getCausalState,getMemory,remember,clearMemory,sendFile,sendImage,removeSelectedFile,restoreConversation,setMode,toggleMode,startNewConversation,renameConversation,deleteConversation};