const API_URL="https://wiener-ia.onrender.com";
const messages=document.getElementById("messages"),userInput=document.getElementById("userInput"),sendBtn=document.getElementById("sendBtn"),newChatBtn=document.getElementById("newChatBtn"),welcome=document.getElementById("welcome");
let history=[],currentMode="chat",lastCausalState=null,memoryCount=0;

function addMessage(content,role){const div=document.createElement("div");div.className=role==="user"?"message user":"message assistant";div.textContent=String(content??"");messages?.appendChild(div);if(messages)messages.scrollTop=messages.scrollHeight;return div;}
function addImageMessage(dataUrl){const div=document.createElement("div");div.className="message assistant";const img=document.createElement("img");img.src=dataUrl;img.alt="Image générée par Wiener IA";img.style.maxWidth="100%";img.style.maxHeight="700px";img.style.borderRadius="12px";img.style.display="block";div.appendChild(img);messages?.appendChild(div);if(messages)messages.scrollTop=messages.scrollHeight;}
function showCausalTrace(causal,extra={}){if(!causal||!messages)return;lastCausalState=causal;const d=causal.D||{},f=causal.F||{},s=causal.S||{};const count=Number(extra.memoryCount??memoryCount??0);const trace=document.createElement("div");trace.className="message assistant";trace.textContent=`Analyse fonctionnelle — D: ${d.task||"unknown"} | pertinence: ${d.relevance||"unknown"} | complexité: ${Number(d.complexity||0).toFixed(2)} | F: profondeur=${f.depth||"normal"}, vérification=${f.verify?"oui":"non"}, recherche=${f.search?"oui":"non"} | mémoire: ${count} éléments | épisodes: ${Number(s.episodes||0)}.`;trace.style.opacity=".72";trace.style.fontSize=".82em";messages.appendChild(trace);messages.scrollTop=messages.scrollHeight;}

async function requestJSON(url,options={},retries=2){let lastError=null;for(let attempt=0;attempt<=retries;attempt++){try{const response=await fetch(url,{...options,cache:"no-store"});const data=await response.json().catch(()=>({}));if(response.ok)return data;const err=new Error(data.error||`Erreur HTTP ${response.status}`);err.status=response.status;if([408,425,429,500,502,503,504].includes(response.status)&&attempt<retries){await new Promise(r=>setTimeout(r,1000*(attempt+1)));continue;}throw err;}catch(error){lastError=error;if(attempt<retries&&!error.status){await new Promise(r=>setTimeout(r,1000*(attempt+1)));continue;}if(attempt<retries&&[408,425,429,500,502,503,504].includes(error.status)){await new Promise(r=>setTimeout(r,1000*(attempt+1)));continue;}throw error;}}throw lastError||new Error("Serveur Wiener IA inaccessible.");}

function removeSelectedFile(){const input=document.getElementById("fileInput"),preview=document.getElementById("filePreview");if(input)input.value="";window.wienerSelectedFile=null;if(preview)preview.hidden=true;if(userInput)userInput.placeholder="Envoyez un message à Wiener IA...";}

document.querySelectorAll(".menu-item").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".menu-item").forEach(b=>b.classList.remove("active"));btn.classList.add("active");currentMode=btn.dataset.mode||"chat";if(currentMode==="image")addMessage("Mode image activé. Décris l'image que tu veux générer.","assistant");if(currentMode==="pdf")addMessage("Mode documents activé. Ajoute un PDF ou une image avec le trombone, puis pose ta question.","assistant");if(currentMode==="search")addMessage("Mode Recherche Web activé. Wiener IA utilisera la recherche Google lorsque nécessaire.","assistant");}));
if(newChatBtn)newChatBtn.addEventListener("click",()=>{history=[];lastCausalState=null;if(messages)messages.innerHTML=`<div class="message assistant">👋 Bonjour !<br><br>Je suis <b>Wiener IA</b>.<br><br>Comment puis-je vous aider aujourd'hui ?</div>`;if(welcome)welcome.style.display="block";if(userInput){userInput.value="";userInput.focus();}removeSelectedFile();});
if(userInput)userInput.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();sendMessage();}});if(sendBtn)sendBtn.addEventListener("click",sendMessage);

async function sendFile(file,prompt){const form=new FormData();form.append("file",file,file.name);form.append("prompt",prompt||"Analyse ce fichier et réponds à ma question.");const data=await requestJSON(API_URL+"/api/analyze-file",{method:"POST",body:form},2);if(data.causal)showCausalTrace(data.causal,data);return data;}
async function sendImage(prompt){const data=await requestJSON(API_URL+"/api/image",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt})},2);if(data.image)addImageMessage(data.image);if(data.causal)showCausalTrace(data.causal,data);return data;}

async function sendMessage(){if(!userInput||!messages)return;const text=userInput.value.trim(),selectedFile=window.wienerSelectedFile||null;if(!text&&!selectedFile)return;if(welcome)welcome.style.display="none";if(text)addMessage(text,"user");userInput.value="";const loading=document.createElement("div");loading.className="message assistant";loading.textContent="⏳ Wiener IA réfléchit...";messages.appendChild(loading);messages.scrollTop=messages.scrollHeight;try{if(selectedFile){const data=await sendFile(selectedFile,text);loading.remove();addMessage(data.answer,"assistant");removeSelectedFile();return;}if(currentMode==="image"){const data=await sendImage(text);loading.remove();if(!data.image)addMessage("Le modèle image n'a pas retourné d'image.","assistant");return;}let endpoint="/api/chat",body,shouldAddToHistory=false;if(currentMode==="exercise"){endpoint="/api/exercises";body={question:text,level:"Non précisé",subject:"Non précisée"};}else if(currentMode==="search"){endpoint="/api/search";body={query:text};}else if(currentMode==="calculator"){endpoint="/api/calculate";body={expression:text};}else if(currentMode==="pdf"){endpoint="/api/analyze";body={text};}else{shouldAddToHistory=true;history.push({role:"user",content:text});body={messages:history};}const data=await requestJSON(API_URL+endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)},2);loading.remove();const answer=data.answer??data.result??data.response??data.analysis??data.text??data.message;if(answer===undefined||answer===null||String(answer).trim()==="")throw new Error("Le serveur n'a retourné aucune réponse.");addMessage(answer,"assistant");if(shouldAddToHistory)history.push({role:"assistant",content:String(answer)});if(Number.isFinite(Number(data.memoryCount)))memoryCount=Number(data.memoryCount);if(data.causal)showCausalTrace(data.causal,data);}catch(error){loading.remove();const msg=error.status===503?"Le service IA est temporairement très sollicité. Wiener IA a automatiquement retenté la requête.":(error.message||"Serveur Wiener IA inaccessible.");addMessage("❌ "+msg,"assistant");console.error("Wiener IA:",error);}}

async function analyzeFunctionally(text){const value=String(text||"").trim();if(!value)return null;const data=await requestJSON(API_URL+"/api/consciousness",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:value})},2);if(data.causal)showCausalTrace(data.causal,data);return data;}
async function getCausalState(){return requestJSON(API_URL+"/api/causal/state",{},1);}
async function getMemory(){const data=await requestJSON(API_URL+"/api/memory",{},1);memoryCount=Number(data.count||0);return data;}
async function remember(content,role="user"){const value=String(content||"").trim();if(!value)return null;const data=await requestJSON(API_URL+"/api/memory",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({content:value,role})},1);memoryCount=Number(data.count||memoryCount);return data;}
async function clearMemory(){const data=await requestJSON(API_URL+"/api/memory",{method:"DELETE"},1);memoryCount=0;return data;}
async function checkServer(){try{const data=await requestJSON(API_URL+"/api/health",{},1);memoryCount=Number(data.memoryCount||0);console.log("Wiener IA connectée :",data);return data.ok===true;}catch(error){console.error("Serveur Wiener IA inaccessible :",error);return false;}}
window.WienerIA={sendMessage,checkServer,analyzeFunctionally,getCausalState,getMemory,remember,clearMemory,sendFile,sendImage,removeSelectedFile};checkServer();
