const API_URL="https://wiener-ia.onrender.com";
const messages=document.getElementById("messages"),userInput=document.getElementById("userInput"),sendBtn=document.getElementById("sendBtn"),newChatBtn=document.getElementById("newChatBtn"),historyList=document.getElementById("historyList"),clearHistoryBtn=document.getElementById("clearHistoryBtn");
let history=[],currentMode="chat",lastCausalState=null,memoryCount=0,currentConversationId=null;
const HISTORY_KEY="wiener_ia_navigation_history_v1";
function scrollChat(){const container=document.getElementById("chatContainer");if(container)container.scrollTo({top:container.scrollHeight,behavior:"auto"});if(messages)messages.scrollIntoView({block:"end",behavior:"auto"});}
function addMessage(content,role){const div=document.createElement("div"),isUser=role==="user";div.className=isUser?"message user":"message assistant";div.dataset.role=isUser?"user":"assistant";const label=document.createElement("div");label.className="message-label";label.textContent=isUser?"Vous":"Wiener IA";const body=document.createElement("div");body.className="message-content";body.textContent=String(content??"");div.append(label,body);messages?.appendChild(div);scrollChat();return div;}
async function typeMessage(content,role="assistant",speed=8){const div=document.createElement("div"),isUser=role==="user";div.className=isUser?"message user":"message assistant";div.dataset.role=isUser?"user":"assistant";const label=document.createElement("div");label.className="message-label";label.textContent=isUser?"Vous":"Wiener IA";const body=document.createElement("div");body.className="message-content";div.append(label,body);messages?.appendChild(div);const text=String(content??"");if(!text){scrollChat();return div;}for(let i=0;i<text.length;i++){body.textContent+=text[i];if(i%3===0)scrollChat();await new Promise(r=>setTimeout(r,speed));}scrollChat();return div;}
function addImageMessage(dataUrl){const div=document.createElement("div");div.className="message assistant";const img=document.createElement("img");img.src=dataUrl;img.alt="Image générée par Wiener IA";img.style.maxWidth="100%";img.style.maxHeight="700px";img.style.borderRadius="12px";img.style.display="block";div.appendChild(img);messages?.appendChild(div);scrollChat();}
function showSearchSources(sources){if(!Array.isArray(sources)||!sources.length||!messages)return;const wrap=document.createElement("div");wrap.className="message assistant search-sources";const title=document.createElement("div");title.textContent="Sources Google";title.style.fontWeight="600";title.style.marginBottom="8px";wrap.appendChild(title);const list=document.createElement("div");sources.slice(0,8).forEach((source,i)=>{const link=document.createElement("a");link.href=source.uri;link.target="_blank";link.rel="noopener noreferrer";link.textContent=`${i+1}. ${source.title||source.uri}`;link.style.display="block";link.style.margin="4px 0";list.appendChild(link);});wrap.appendChild(list);messages.appendChild(wrap);scrollChat();}
function loadNavigationHistory(){try{const raw=localStorage.getItem(HISTORY_KEY);const items=raw?JSON.parse(raw):[];return Array.isArray(items)?items:[];}catch(_){return [];}}
function saveNavigationHistory(items){try{localStorage.setItem(HISTORY_KEY,JSON.stringify(items.slice(0,30)));}catch(_){} }
function renderNavigationHistory(){if(!historyList)return;const items=loadNavigationHistory();historyList.innerHTML="";if(!items.length){historyList.innerHTML='<div class="history-empty">Aucune conversation récente</div>';return;}items.forEach(item=>{const button=document.createElement("button");button.type="button";button.className="history-item";button.dataset.id=item.id;button.innerHTML=`<span class="history-title"></span><small></small>`;button.querySelector(".history-title").textContent=item.title;button.querySelector("small").textContent=new Date(item.updatedAt).toLocaleDateString("fr-FR");button.addEventListener("click",()=>restoreConversation(item.id));historyList.appendChild(button);});}
function saveCurrentConversation(){const visible=[...messages.querySelectorAll(".message")].map(m=>({role:m.classList.contains("user")?"user":"assistant",content:m.textContent||""})).filter(x=>x.content.trim());const userFirst=visible.find(x=>x.role==="user");if(!userFirst)return;const items=loadNavigationHistory();const id=currentConversationId||String(Date.now());currentConversationId=id;const existing=items.find(x=>x.id===id);const item={id,title:userFirst.content.slice(0,55)+(userFirst.content.length>55?"…":""),updatedAt:new Date().toISOString(),history,mode:currentMode};if(existing)Object.assign(existing,item);else items.unshift(item);saveNavigationHistory(items);renderNavigationHistory();}
function restoreConversation(id){const item=loadNavigationHistory().find(x=>x.id===id);if(!item||!messages)return;currentConversationId=item.id;history=Array.isArray(item.history)?item.history:[];currentMode=item.mode||"chat";messages.innerHTML="";history.forEach(m=>{const div=document.createElement("div");div.className=m.role==="user"?"message user":"message assistant";div.textContent=String(m.content||"");messages.appendChild(div);});document.querySelectorAll(".menu-item,.plus-menu button[data-mode]").forEach(b=>b.classList.toggle("active",(b.dataset.mode||"chat")==currentMode));scrollChat();}
async function requestJSON(url,options={},retries=2){let lastError=null;for(let attempt=0;attempt<=retries;attempt++){try{const response=await fetch(url,{...options,cache:"no-store"});const data=await response.json().catch(()=>({}));if(response.ok)return data;const err=new Error(data.error||`Erreur HTTP ${response.status}`);err.status=response.status;if([408,425,429,500,502,503,504].includes(response.status)&&attempt<retries){await new Promise(r=>setTimeout(r,1000*(attempt+1)));continue;}throw err;}catch(error){lastError=error;if(attempt<retries&&!error.status){await new Promise(r=>setTimeout(r,1000*(attempt+1)));continue;}if(attempt<retries&&[408,425,429,500,502,503,504].includes(error.status)){await new Promise(r=>setTimeout(r,1000*(attempt+1)));continue;}throw error;}}throw lastError||new Error("Serveur Wiener IA inaccessible.");}
function setMode(mode){currentMode=mode||"chat";document.querySelectorAll(".menu-item,.plus-menu button[data-mode]").forEach(b=>b.classList.toggle("active",(b.dataset.mode||"chat")==currentMode));if(currentMode==="image")addMessage("Mode image activé. Décris l'image que tu veux générer.","assistant");if(currentMode==="pdf")addMessage("Mode documents activé. Ajoute un fichier avec le bouton +, puis pose ta question.","assistant");if(currentMode==="search")addMessage("Recherche Google activée. Wiener IA va rechercher les informations actuelles et afficher les sources utilisées.","assistant");}
function toggleMode(mode){const next=mode===currentMode?"chat":mode;setMode(next);if(next==="chat")addMessage("Mode spécial désactivé. Retour au chat normal.","assistant");}
function removeSelectedFile(){const input=document.getElementById("fileInput"),preview=document.getElementById("filePreview");if(input)input.value="";window.wienerSelectedFile=null;if(preview)preview.hidden=true;if(userInput)userInput.placeholder="Envoyez un message à Wiener IA...";}
document.querySelectorAll(".plus-menu button[data-mode]").forEach(btn=>btn.addEventListener("click",()=>{const mode=btn.dataset.mode||"chat";toggleMode(mode);}));
document.querySelectorAll(".menu-item[data-mode]").forEach(btn=>btn.addEventListener("click",()=>toggleMode(btn.dataset.mode||"chat")));
if(clearHistoryBtn)clearHistoryBtn.addEventListener("click",()=>{localStorage.removeItem(HISTORY_KEY);currentConversationId=null;renderNavigationHistory();});
if(newChatBtn)newChatBtn.addEventListener("click",()=>{history=[];lastCausalState=null;currentConversationId=null;setMode("chat");if(messages)messages.innerHTML=`<div class="message assistant"><div class="message-content">👋 Bonjour !<br><br>Je suis <strong>Wiener IA</strong>.<br><br>Comment puis-je vous aider aujourd'hui ?</div></div>`;if(userInput){userInput.value="";userInput.focus();}removeSelectedFile();});
if(userInput)userInput.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();sendMessage();}});if(sendBtn)sendBtn.addEventListener("click",sendMessage);
async function sendFile(file,prompt){const form=new FormData();form.append("file",file,file.name);form.append("prompt",prompt||"Analyse ce fichier et réponds à ma question.");const data=await requestJSON(API_URL+"/api/analyze-file",{method:"POST",body:form},2);return data;}
async function sendImage(prompt){const data=await requestJSON(API_URL+"/api/image",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt})},2);if(data.image)addImageMessage(data.image);return data;}
async function sendMessage(){if(!userInput||!messages)return;const text=userInput.value.trim(),selectedFile=window.wienerSelectedFile||null;if(!text&&!selectedFile)return;const submittedText=text||"Fichier envoyé";if(text)addMessage(text,"user");userInput.value="";const loading=document.createElement("div");loading.className="message assistant";loading.dataset.role="assistant";loading.innerHTML="<div class=\"message-label\">Wiener IA</div><div class=\"message-content typing-dots\" aria-label=\"Wiener IA traite la demande\"><span>.</span><span>.</span><span>.</span></div>";messages.appendChild(loading);scrollChat();try{if(selectedFile){const data=await sendFile(selectedFile,text);loading.remove();await typeMessage(data.answer,"assistant",6);removeSelectedFile();saveCurrentConversation();return;}if(currentMode==="image"){const data=await sendImage(text);loading.remove();if(!data.image)await typeMessage("Le modèle image n'a pas retourné d'image.","assistant",8);saveCurrentConversation();return;}let endpoint="/api/chat",body,shouldAddToHistory=false;if(currentMode==="exercise"){endpoint="/api/exercises";body={question:text,level:"Non précisé",subject:"Non précisée"};}else if(currentMode==="search"){endpoint="/api/search";body={query:text};}else if(currentMode==="calculator"){endpoint="/api/calculate";body={expression:text};}else if(currentMode==="pdf"){endpoint="/api/analyze";body={text};}else{shouldAddToHistory=true;history.push({role:"user",content:text});body={messages:history};}const data=await requestJSON(API_URL+endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)},2);loading.remove();const answer=data.answer??data.result??data.response??data.analysis??data.text??data.message;if(answer===undefined||answer===null||String(answer).trim()==="")throw new Error("Le serveur n'a retourné aucune réponse.");await typeMessage(answer,"assistant",6);if(currentMode==="search"&&Array.isArray(data.sources))showSearchSources(data.sources);if(shouldAddToHistory)history.push({role:"assistant",content:String(answer)});if(Number.isFinite(Number(data.memoryCount)))memoryCount=Number(data.memoryCount);saveCurrentConversation();}catch(error){loading.remove();const msg=error.status===503?"Le service IA est temporairement très sollicité. Wiener IA a automatiquement retenté la requête.":(error.message||"Serveur Wiener IA inaccessible.");await typeMessage("❌ "+msg,"assistant",4);console.error("Wiener IA:",error);}}
async function analyzeFunctionally(text){const value=String(text||"").trim();if(!value)return null;const data=await requestJSON(API_URL+"/api/consciousness",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:value})},2);return data;}
async function getCausalState(){return requestJSON(API_URL+"/api/causal/state",{},1);}
async function getMemory(){const data=await requestJSON(API_URL+"/api/memory",{},1);memoryCount=Number(data.count||0);return data;}
async function remember(content,role="user"){const value=String(content||"").trim();if(!value)return null;const data=await requestJSON(API_URL+"/api/memory",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({content:value,role})},1);memoryCount=Number(data.count||memoryCount);return data;}
async function clearMemory(){const data=await requestJSON(API_URL+"/api/memory",{method:"DELETE"},1);memoryCount=0;return data;}
async function checkServer(){try{const data=await requestJSON(API_URL+"/api/health",{},1);memoryCount=Number(data.memoryCount||0);console.log("Wiener IA connectée :",data);return data.ok===true;}catch(error){console.error("Wiener IA inaccessible :",error);return false;}}
renderNavigationHistory();checkServer();
window.WienerIA={sendMessage,checkServer,analyzeFunctionally,getCausalState,getMemory,remember,clearMemory,sendFile,sendImage,removeSelectedFile,restoreConversation,setMode,toggleMode};
