"use strict";
(() => {
  const API="https://wiener-ia.onrender.com";
  const esc=s=>String(s??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
  const css=`#wienerAuthButton{margin-left:12px;border:1px solid rgba(255,255,255,.12);background:#171717;color:#fff;border-radius:10px;padding:8px 13px;cursor:pointer;font:500 13px Inter,system-ui,sans-serif}#wienerAuthButton:hover{background:#262626}#wienerAuthModal{position:fixed;inset:0;z-index:100000;display:none;align-items:center;justify-content:center;background:rgba(0,0,0,.58);padding:20px;font-family:Inter,system-ui,sans-serif}#wienerAuthModal.open{display:flex}.wa-card{width:min(420px,100%);background:#212121;color:#fff;border:1px solid rgba(255,255,255,.1);border-radius:16px;padding:24px;box-shadow:0 20px 70px rgba(0,0,0,.45)}.wa-card h2{margin:0 0 6px;font-size:22px}.wa-card p{margin:0 0 18px;color:#aaa;font-size:13px}.wa-tabs{display:flex;gap:6px;margin-bottom:16px}.wa-tabs button{flex:1;padding:9px;border:0;border-radius:8px;background:#303030;color:#aaa;cursor:pointer}.wa-tabs button.active{background:#10A37F;color:#fff}.wa-card label{display:block;font-size:12px;color:#aaa;margin:10px 0 5px}.wa-card input{width:100%;box-sizing:border-box;background:#171717;color:#fff;border:1px solid #3a3a3a;border-radius:9px;padding:11px;outline:none}.wa-card input:focus{border-color:#10A37F}.wa-primary{width:100%;margin-top:14px;padding:11px;border:0;border-radius:9px;background:#10A37F;color:#fff;font-weight:600;cursor:pointer}.wa-google{width:100%;margin-top:9px;padding:11px;border:1px solid #444;border-radius:9px;background:#fff;color:#222;font-weight:600;cursor:pointer}.wa-close{float:right;border:0;background:transparent;color:#aaa;font-size:22px;cursor:pointer}.wa-error{min-height:18px;margin-top:10px;color:#ff8f8f;font-size:12px}.wa-user{display:flex;align-items:center;gap:8px}.wa-avatar{width:28px;height:28px;border-radius:50%;object-fit:cover}.wa-logout{border:0;background:transparent;color:#aaa;cursor:pointer;font-size:12px}`;
  function addStyles(){if(document.getElementById("wienerAuthStyles"))return;const s=document.createElement("style");s.id="wienerAuthStyles";s.textContent=css;document.head.appendChild(s);}
  async function api(path,options={}){const response=await fetch(API+path,{...options,credentials:"include",headers:{"Content-Type":"application/json",...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`Erreur HTTP ${response.status}`);return data;}
  function createUI(){addStyles();const top=document.querySelector(".topbar .topbar-left")||document.querySelector(".topbar");if(!top)return;const button=document.createElement("button");button.id="wienerAuthButton";button.type="button";button.textContent="Se connecter";top.appendChild(button);const modal=document.createElement("div");modal.id="wienerAuthModal";modal.innerHTML=`<div class="wa-card"><button class="wa-close" type="button" aria-label="Fermer">×</button><h2 id="waTitle">Connexion à Wiener IA</h2><p>Retrouve ton compte et tes conversations sur tes appareils.</p><div class="wa-tabs"><button type="button" data-tab="login" class="active">Connexion</button><button type="button" data-tab="register">Créer un compte</button></div><form id="waForm"><div id="waNameWrap" style="display:none"><label for="waName">Nom</label><input id="waName" autocomplete="name" maxlength="100"></div><label for="waEmail">E-mail</label><input id="waEmail" type="email" autocomplete="email" required><label for="waPassword">Mot de passe</label><input id="waPassword" type="password" autocomplete="current-password" minlength="8" maxlength="128" required><button class="wa-primary" type="submit">Continuer</button></form><button id="waGoogle" class="wa-google" type="button">Continuer avec Google</button><div id="waError" class="wa-error"></div></div>`;document.body.appendChild(modal);let tab="login";const form=modal.querySelector("#waForm"),nameWrap=modal.querySelector("#waNameWrap"),password=modal.querySelector("#waPassword"),error=modal.querySelector("#waError");function setTab(next){tab=next;modal.querySelectorAll(".wa-tabs button").forEach(b=>b.classList.toggle("active",b.dataset.tab===tab));nameWrap.style.display=tab==="register"?"block":"none";password.autocomplete=tab==="register"?"new-password":"current-password";form.querySelector(".wa-primary").textContent=tab==="register"?"Créer mon compte":"Se connecter";error.textContent="";}modal.querySelector(".wa-close").onclick=()=>modal.classList.remove("open");modal.addEventListener("click",e=>{if(e.target===modal)modal.classList.remove("open")});modal.querySelectorAll(".wa-tabs button").forEach(b=>b.onclick=()=>setTab(b.dataset.tab));button.onclick=()=>modal.classList.add("open");form.onsubmit=async e=>{e.preventDefault();error.textContent="";try{const body={email:modal.querySelector("#waEmail").value,password:password.value};if(tab==="register")body.name=modal.querySelector("#waName").value;const data=await api(tab==="register"?"/api/auth/register":"/api/auth/login",{method:"POST",body:JSON.stringify(body)});modal.classList.remove("open");renderUser(data.user);}catch(err){error.textContent=err.message;}};modal.querySelector("#waGoogle").onclick=()=>{window.location.href=API+"/api/auth/google"};return {button,modal};}
  function renderUser(user){const button=document.getElementById("wienerAuthButton");if(!button)return;if(!user){button.textContent="Se connecter";button.onclick=()=>document.getElementById("wienerAuthModal")?.classList.add("open");return;}button.className="wa-user";button.innerHTML=`${user.avatarUrl?`<img class="wa-avatar" src="${esc(user.avatarUrl)}" alt="">`:""}<span>${esc(user.name||user.email)}</span>`;button.onclick=async()=>{if(confirm("Se déconnecter de Wiener IA ?")){await api("/api/auth/logout",{method:"POST",body:"{}"}).catch(()=>{});location.reload();}};}
  async function init(){const ui=createUI();if(!ui)return;try{const data=await api("/api/auth/me");renderUser(data.user);}catch{renderUser(null);}const params=new URLSearchParams(location.search);if(params.get("auth")){history.replaceState({},document.title,location.pathname+location.hash);if(params.get("auth")==="error")alert("La connexion Google n'a pas abouti.");}}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
})();
