"use strict";
const express=require("express"),cors=require("cors"),path=require("path"),fs=require("fs"),crypto=require("crypto");
const {GoogleGenAI}=require("@google/genai"),multer=require("multer"),cloud=require("./cloud-services");
const app=express(),PORT=Number(process.env.PORT)||10000,API_KEY=process.env.GEMINI_API_KEY,TEXT_MODEL="gemini-3.5-flash-lite",IMAGE_MODELS=[process.env.GEMINI_IMAGE_MODEL||"gemini-3.1-flash-image","gemini-2.5-flash-image"],MAX_MESSAGES=8,MAX_MESSAGE_LENGTH=8000,MAX_FILE_SIZE=50*1024*1024,REQUEST_TIMEOUT=90000,ai=API_KEY?new GoogleGenAI({apiKey:API_KEY}):null;
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:MAX_FILE_SIZE}});
app.disable("x-powered-by");app.use(cors({origin:true,methods:["GET","POST","OPTIONS"],allowedHeaders:["Content-Type","Authorization","X-User-ID","X-Conversation-ID"]}));app.use(express.json({limit:"8mb"}));app.use(express.static(__dirname,{index:false}));
const BASE_INSTRUCTIONS=`Tu es Wiener IA, un assistant généraliste intelligent, précis, pédagogique et naturel. Réponds en français par défaut. Comprends la demande avant de répondre. Sois direct et structuré. N'invente jamais de faits, de sources ou d'actions réalisées. N'expose jamais les secrets ou clés API.`;
const EXERCISE_INSTRUCTIONS=`Résous l'exercice avec rigueur. Donne la méthode, les calculs essentiels et la réponse finale clairement.`;
const ANALYSIS_INSTRUCTIONS=`Analyse la demande de façon fonctionnelle et utile. Ne présente jamais cette analyse comme une conscience biologique ou une expérience subjective.`;
const SEARCH_INSTRUCTIONS=`Tu es le module Recherche Web de Wiener IA. Utilise Google Search pour obtenir des informations actuelles et vérifiables. Distingue les faits trouvés des déductions et cite les sources utilisées.`;
function statusOf(e){return Number(e?.status)||Number(e?.statusCode)||Number(e?.response?.status)||500}
function requireAI(res){if(!ai){res.status(503).json({error:"GEMINI_API_KEY est manquante."});return false}return true}
function cleanMessages(messages){if(!Array.isArray(messages))return[];return messages.filter(m=>m&&typeof m==="object"&&["user","assistant","model"].includes(m.role)&&typeof m.content==="string"&&m.content.trim()).map(m=>({role:m.role==="assistant"||m.role==="model"?"model":"user",content:m.content.trim().slice(0,MAX_MESSAGE_LENGTH)})).slice(-MAX_MESSAGES)}
function toGemini(messages){return messages.map(m=>({role:m.role,parts:[{text:m.content}]}))}
function textOf(r){if(typeof r?.text==="string"&&r.text.trim())return r.text.trim();const p=r?.candidates?.flatMap(c=>Array.isArray(c?.content?.parts)?c.content.parts:[])||[];return p.filter(x=>typeof x?.text==="string").map(x=>x.text).join("\n").trim()}
function interactionText(x){if(typeof x?.output_text==="string"&&x.output_text.trim())return x.output_text.trim();const b=x?.steps?.flatMap(s=>s?.type==="model_output"?(s.content||[]):[])||[];return b.filter(x=>x?.type==="text"&&typeof x.text==="string").map(x=>x.text).join("\n").trim()}
function chunkText(c){if(typeof c?.text==="string")return c.text;const p=c?.candidates?.flatMap(x=>Array.isArray(x?.content?.parts)?x.content.parts:[])||[];return p.filter(x=>typeof x?.text==="string").map(x=>x.text).join("")}
function groundingOf(r){const m=r?.candidates?.[0]?.groundingMetadata||r?.groundingMetadata||null,chunks=Array.isArray(m?.groundingChunks)?m.groundingChunks:[];const sources=chunks.map((c,i)=>{const w=c?.web||c?.retrievedContext;return w?.uri?{index:i,title:w.title||new URL(w.uri).hostname,uri:w.uri}:null}).filter(Boolean);return{metadata:m,sources,supports:Array.isArray(m?.groundingSupports)?m.groundingSupports:[]}}
function textConfig(config){const c={...(config||{})};delete c.temperature;delete c.topP;delete c.topK;c.thinkingConfig={thinkingLevel:"minimal"};return c}
async function withTimeout(p,ms=REQUEST_TIMEOUT){let t;const timeout=new Promise((_,r)=>t=setTimeout(()=>r(Object.assign(new Error("Le service IA met trop de temps à répondre."),{status:504})),ms));try{return await Promise.race([p,timeout])}finally{clearTimeout(t)}}
async function generate(o){return{response:await withTimeout(ai.models.generateContent({...o,model:TEXT_MODEL,config:textConfig(o.config)})),model:TEXT_MODEL}}
async function generateStream(o,res){const stream=await withTimeout(ai.models.generateContentStream({...o,model:TEXT_MODEL,config:textConfig(o.config)}));res.write(`event: start\ndata: ${JSON.stringify({model:TEXT_MODEL})}\n\n`);let full="";for await(const c of stream){const text=chunkText(c);if(text){full+=text;res.write(`data: ${JSON.stringify({text})}\n\n`)}}if(!full.trim())throw Error("Wiener IA n'a retourné aucune réponse.");res.write(`event: done\ndata: ${JSON.stringify({answer:full.trim(),model:TEXT_MODEL})}\n\n`);res.end();return full.trim()}
async function generateImage(prompt){let last=null;for(const model of [...new Set(IMAGE_MODELS)]){try{const x=await withTimeout(ai.interactions.create({model,input:prompt})),d=x?.output_image?.data;if(d)return{data:d,mime:x?.output_image?.mime_type||"image/png",model};const b=x?.steps?.flatMap(s=>s?.type==="model_output"?(s.content||[]):[]).find(c=>c?.type==="image"&&c?.data);if(b)return{data:b.data,mime:b.mime_type||"image/png",model};throw Error("Aucune image.")}catch(e){last=e;if(![404,408,425,429,500,502,503,504].includes(statusOf(e)))throw e}}throw last||Error("Aucun modèle image disponible.")}
async function analyzeFile(file,prompt){const data=file.buffer.toString("base64"),input=[{type:"text",text:prompt}];if(file.mimetype==="application/pdf")input.push({type:"document",data,mime_type:file.mimetype});else input.push({type:"image",data,mime_type:file.mimetype});const x=await withTimeout(ai.interactions.create({model:TEXT_MODEL,input}));return{answer:interactionText(x),model:x?.model||TEXT_MODEL}}
async function persist(fn){try{await fn()}catch(e){console.error("Wiener IA persistence:",e?.message||e)}}
async function context(req){const auth=await cloud.getAuthUser(req);return{userId:auth?.uid||cloud.getUserId(req),email:auth?.email||null,conversationId:cloud.getConversationId(req)}}
function sendError(res,e){console.error("Wiener IA:",e?.message||e);const s=statusOf(e);if(s===401||s===403)return res.status(s).json({error:"Authentification ou clé Gemini invalide."});if(s===404)return res.status(404).json({error:"Service demandé indisponible."});if(s===429)return res.status(429).json({error:"Service temporairement limité."});if(s===408||s===504)return res.status(504).json({error:"Le service IA met trop de temps à répondre."});return res.status(s>=500?500:s).json({error:e?.message||"Erreur serveur."})}
async function firebaseAuth(action,email,password){const key=process.env.FIREBASE_WEB_API_KEY;if(!key)throw Object.assign(Error("FIREBASE_WEB_API_KEY n'est pas configurée sur Render."),{status:503});const url=`https://identitytoolkit.googleapis.com/v1/accounts:${action}?key=${encodeURIComponent(key)}`;const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password,returnSecureToken:true})});const data=await r.json();if(!r.ok){const map={EMAIL_EXISTS:"Cet email est déjà utilisé.",EMAIL_NOT_FOUND:"Email ou mot de passe incorrect.",INVALID_PASSWORD:"Email ou mot de passe incorrect.",WEAK_PASSWORD:"Mot de passe trop faible."};throw Object.assign(Error(map[data?.error?.message]||"Authentification impossible."),{status:r.status})}return data}
app.get("/",(_,res)=>{try{let html=fs.readFileSync(path.join(__dirname,"index.html"),"utf8");const old="let bubble=typing.querySelector('.assistantBubble');bubble.innerHTML='';let stream=await streamChat";const fixed="let bubble=typing.querySelector('.assistantBubble');let stream=await streamChat";if(html.includes(old))html=html.replace(old,fixed);res.type("html").send(html)}catch(e){res.status(500).send("Wiener IA indisponible.")}});
app.get("/health",(_,res)=>res.json({ok:true,service:"Wiener IA",geminiConfigured:Boolean(ai),firebaseConfigured:cloud.firebaseReady,cloudinaryConfigured:cloud.cloudinaryReady,authConfigured:Boolean(process.env.FIREBASE_WEB_API_KEY),model:TEXT_MODEL,time:new Date().toISOString()}));
app.get("/api/health",(_,res)=>res.json({ok:true,service:"Wiener IA",geminiConfigured:Boolean(ai),firebaseConfigured:cloud.firebaseReady,cloudinaryConfigured:cloud.cloudinaryReady,authConfigured:Boolean(process.env.FIREBASE_WEB_API_KEY),textModel:TEXT_MODEL,time:new Date().toISOString()}));
app.get("/api/session",async(req,res)=>{const existing=cloud.getUserId(req),userId=existing||crypto.randomUUID();await persist(()=>cloud.ensureUser(userId));res.json({ok:true,userId,firebaseConfigured:cloud.firebaseReady,cloudinaryConfigured:cloud.cloudinaryReady})});
app.post("/api/auth/signup",async(req,res)=>{try{const email=String(req.body?.email||"").trim().toLowerCase(),password=String(req.body?.password||"");if(!email||password.length<6)return res.status(400).json({error:"Email et mot de passe (6 caractères minimum) requis."});const d=await firebaseAuth("signUp",email,password);await persist(()=>cloud.ensureUser(d.localId,email));res.json({ok:true,email:d.email,userId:d.localId,idToken:d.idToken,refreshToken:d.refreshToken,expiresIn:d.expiresIn})}catch(e){sendError(res,e)}});
app.post("/api/auth/login",async(req,res)=>{try{const email=String(req.body?.email||"").trim().toLowerCase(),password=String(req.body?.password||"");if(!email||!password)return res.status(400).json({error:"Email et mot de passe requis."});const d=await firebaseAuth("signInWithPassword",email,password);await persist(()=>cloud.ensureUser(d.localId,email));res.json({ok:true,email:d.email,userId:d.localId,idToken:d.idToken,refreshToken:d.refreshToken,expiresIn:d.expiresIn})}catch(e){sendError(res,e)}});
app.get("/api/auth/me",async(req,res)=>{const u=await cloud.getAuthUser(req);if(!u)return res.status(401).json({authenticated:false});res.json({authenticated:true,userId:u.uid,email:u.email||null})});
app.get("/api/conversations",async(req,res)=>{try{const {userId}=await context(req);if(!userId)return res.status(401).json({error:"Authentification requise."});res.json({conversations:await cloud.listConversations(userId)})}catch(e){res.status(500).json({error:"Impossible de charger les conversations."})}});
app.get("/api/conversations/:id/messages",async(req,res)=>{try{const {userId}=await context(req),conversationId=String(req.params.id||"");if(!userId||!conversationId)return res.status(400).json({error:"Identifiant manquant."});res.json({messages:await cloud.listMessages(userId,conversationId)})}catch(e){res.status(500).json({error:"Impossible de charger l'historique."})}});
app.post("/api/chat",async(req,res)=>{try{if(!requireAI(res))return;let messages=cleanMessages(req.body?.messages);if(!messages.length&&typeof req.body?.message==="string"&&req.body.message.trim())messages=[{role:"user",content:req.body.message.trim()}];if(!messages.length)return res.status(400).json({error:"Aucun message valide."});const {userId,conversationId,email}=await context(req),lastUser=[...messages].reverse().find(m=>m.role==="user");if(userId&&conversationId&&lastUser)await persist(()=>cloud.saveMessage({userId,conversationId,role:"user",content:lastUser.content}));res.setHeader("Content-Type","text/event-stream; charset=utf-8");res.setHeader("Cache-Control","no-cache, no-transform");res.setHeader("Connection","keep-alive");res.flushHeaders?.();const answer=await generateStream({contents:toGemini(messages),config:{systemInstruction:BASE_INSTRUCTIONS,maxOutputTokens:768}},res);if(userId&&conversationId)await persist(()=>cloud.saveMessage({userId,conversationId,role:"assistant",content:answer}))}catch(e){if(res.headersSent){res.write(`event: error\ndata: ${JSON.stringify({error:e?.message||"Réponse interrompue."})}\n\n`);res.end()}else sendError(res,e)}});
app.post("/api/exercises",async(req,res)=>{try{if(!requireAI(res))return;const q=String(req.body?.question||req.body?.message||"").trim();if(!q)return res.status(400).json({error:"Aucun exercice."});const r=await generate({contents:[{role:"user",parts:[{text:q}]}],config:{systemInstruction:EXERCISE_INSTRUCTIONS,maxOutputTokens:1536}}),answer=textOf(r.response);if(!answer)return res.status(502).json({error:"Aucune solution."});const {userId,conversationId}=await context(req);if(userId&&conversationId){await persist(()=>cloud.saveMessage({userId,conversationId,role:"user",content:q,mode:"exercise"}));await persist(()=>cloud.saveMessage({userId,conversationId,role:"assistant",content:answer,mode:"exercise"}))}res.json({answer,model:r.model})}catch(e){sendError(res,e)}});
app.post("/api/calculate",(req,res)=>{const expression=String(req.body?.expression||"").trim();if(!expression)return res.status(400).json({error:"Expression vide."});if(expression.length>500||!/^[0-9+\-*/().,%\s^]+$/.test(expression))return res.status(400).json({error:"Expression non prise en charge."});try{const tokens=expression.replace(/,/g,".").match(/(?:\d+(?:\.\d*)?|\.\d+)|[()+\-*/^%]/g)||[];let i=0;const p=()=>tokens[i],t=()=>tokens[i++];function a(){let v=m();while(["+","-"].includes(p())){const o=t(),r=m();v=o==="+"?v+r:v-r}return v}function m(){let v=u();while(["*","/","%"].includes(p())){const o=t(),r=u();if(o==="/"){if(r===0)throw Error();v/=r}else if(o==="*")v*=r;else v%=r}return v}function u(){if(p()==="-"){t();return-u()}if(p()==="+"){t();return u()}if(p()==="("){t();const v=a();if(t()!==")")throw Error();return v}return Number(t())}const result=a();if(i!==tokens.length||!Number.isFinite(result))throw Error();res.json({result:String(result)})}catch{res.status(400).json({error:"Expression mathématique invalide."})}});
app.post("/api/search",async(req,res)=>{try{if(!requireAI(res))return;const query=String(req.body?.query||"").trim();if(!query)return res.status(400).json({error:"Recherche vide."});const r=await generate({contents:query,config:{systemInstruction:SEARCH_INSTRUCTIONS,tools:[{googleSearch:{}}],maxOutputTokens:1536}}),answer=textOf(r.response),g=groundingOf(r.response);res.json({answer,response:answer,model:r.model,search:true,groundingMetadata:g.metadata,sources:g.sources,supports:g.supports,queries:g.metadata?.webSearchQueries||g.metadata?.searchQueries||[]})}catch(e){sendError(res,e)}});
app.post("/api/image",async(req,res)=>{try{if(!requireAI(res))return;const prompt=String(req.body?.prompt||"").trim();if(!prompt)return res.status(400).json({error:"Décris l'image à générer."});const r=await generateImage(prompt),{userId,conversationId}=await context(req);let media=null;if(cloud.cloudinaryReady)try{media=await cloud.saveGeneratedImage({userId,conversationId,base64:r.data,mimeType:r.mime,prompt})}catch(e){console.error("Cloudinary generated image:",e.message)}if(userId&&conversationId)await persist(()=>cloud.saveMessage({userId,conversationId,role:"user",content:prompt,mode:"image",attachments:media?[media]:[]}));res.json({ok:true,model:r.model,mimeType:r.mime,image:media?.url||`data:${r.mime};base64,${r.data}`,media})}catch(e){sendError(res,e)}});
app.post("/api/upload",upload.single("file"),async(req,res)=>{try{if(!req.file)return res.status(400).json({error:"Aucun fichier reçu."});const mime=req.file.mimetype||"",allowed=/^(image\/(png|jpeg|webp|gif)|video\/(mp4|webm|quicktime|x-msvideo))$/i;if(!allowed.test(mime))return res.status(415).json({error:"Seuls les images et vidéos sont acceptées."});const {userId,conversationId}=await context(req);if(!userId)return res.status(401).json({error:"Connecte-toi pour envoyer un média."});if(!cloud.cloudinaryReady)return res.status(503).json({error:"Cloudinary n'est pas configuré sur Render."});const media=await cloud.saveMedia({userId,conversationId,file:req.file,source:"user_upload",folder:"wiener-ia/uploads"});if(conversationId)await persist(()=>cloud.saveMessage({userId,conversationId,role:"user",content:req.body?.caption||`Média envoyé : ${req.file.originalname}`,mode:"media",attachments:[media]}));res.json({ok:true,media})}catch(e){if(e?.code==="LIMIT_FILE_SIZE")return res.status(413).json({error:"Fichier trop volumineux. Maximum 50 MB."});sendError(res,e)}});
app.post("/api/analyze-file",upload.single("file"),async(req,res)=>{try{if(!requireAI(res))return;if(!req.file)return res.status(400).json({error:"Aucun fichier reçu."});const mime=req.file.mimetype||"",allowed=["application/pdf","image/png","image/jpeg","image/webp"];if(!allowed.includes(mime))return res.status(415).json({error:"PDF ou image uniquement pour l'analyse IA."});const prompt=String(req.body?.prompt||"Analyse ce fichier et réponds clairement à la demande.").trim(),{userId,conversationId}=await context(req);let media=null;if(cloud.cloudinaryReady)try{media=await cloud.saveMedia({userId,conversationId,file:req.file,source:"analysis",folder:"wiener-ia/uploads"})}catch(e){console.error("Cloudinary upload:",e.message)}const r=await analyzeFile(req.file,prompt);if(!r.answer)return res.status(502).json({error:"Aucune analyse."});res.json({answer:r.answer,model:r.model,file:{name:req.file.originalname,mimeType:mime,size:req.file.size},media})}catch(e){sendError(res,e)}});
app.post("/api/consciousness",async(req,res)=>{try{if(!requireAI(res))return;const text=String(req.body?.text||"").trim(),r=await generate({contents:text,config:{systemInstruction:ANALYSIS_INSTRUCTIONS,maxOutputTokens:768}});res.json({analysis:textOf(r.response),functional:true,model:r.model})}catch(e){sendError(res,e)}});
app.post("/api/analyze",async(req,res)=>{try{if(!requireAI(res))return;const text=String(req.body?.text||"").trim(),r=await generate({contents:text,config:{systemInstruction:ANALYSIS_INSTRUCTIONS,maxOutputTokens:768}});res.json({analysis:textOf(r.response),functional:true,model:r.model})}catch(e){sendError(res,e)}});
app.use((err,req,res,next)=>{if(err?.code==="LIMIT_FILE_SIZE")return res.status(413).json({error:"Fichier trop volumineux. Maximum 50 MB."});console.error("Wiener IA middleware:",err?.message||err);if(res.headersSent)return next(err);res.status(500).json({error:"Erreur serveur."})});
app.listen(PORT,"0.0.0.0",()=>console.log(`Wiener IA démarré sur 0.0.0.0:${PORT}`));
