"use strict";
const express=require("express");
const cors=require("cors");
const path=require("path");
const {GoogleGenAI}=require("@google/genai");
const multer=require("multer");
const app=express();
const PORT=Number(process.env.PORT)||10000;
const API_KEY=process.env.GEMINI_API_KEY;
const TEXT_MODEL=process.env.GEMINI_TEXT_MODEL||"gemini-3.5-flash-lite";
const FALLBACK_MODELS=[TEXT_MODEL,"gemini-2.5-flash"].filter((v,i,a)=>v&&a.indexOf(v)===i);
const IMAGE_MODELS=[process.env.GEMINI_IMAGE_MODEL||"gemini-3.1-flash-image","gemini-2.5-flash-image"];
const MAX_MESSAGES=8,MAX_MESSAGE_LENGTH=8000,MAX_FILE_SIZE=20*1024*1024;
const ai=API_KEY?new GoogleGenAI({apiKey:API_KEY}):null;
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:MAX_FILE_SIZE}});
app.disable("x-powered-by");
app.use(cors({origin:true,methods:["GET","POST","OPTIONS"],allowedHeaders:["Content-Type"]}));
app.use(express.json({limit:"6mb"}));
app.use(express.static(__dirname));
const BASE_INSTRUCTIONS=`Tu es Wiener IA, un assistant généraliste intelligent, précis, pédagogique et naturel. Réponds en français par défaut. Comprends la demande avant de répondre. Sois direct et concis pour une demande simple, structuré pour une demande complexe. N'invente jamais de faits, de sources ou d'actions réalisées. N'expose jamais les secrets ou clés API.`;
const EXERCISE_INSTRUCTIONS=`Résous l'exercice avec rigueur. Donne la méthode, les calculs essentiels et la réponse finale clairement. N'invente aucune donnée manquante.`;
const ANALYSIS_INSTRUCTIONS=`Analyse la demande de façon fonctionnelle et utile. Ne présente jamais cette analyse comme une conscience biologique ou une expérience subjective.`;
const SEARCH_INSTRUCTIONS=`Tu es le module Recherche Web de Wiener IA. Utilise Google Search pour obtenir des informations actuelles et vérifiables. Distingue les faits trouvés des déductions et ne fabrique jamais de source. Réponds en français par défaut et cite les sources utilisées.`;
function statusOf(e){return Number(e?.status)||Number(e?.statusCode)||Number(e?.response?.status)||500}
function requireAI(res){if(!ai){res.status(503).json({error:"Le serveur IA n'est pas configuré: GEMINI_API_KEY est manquante."});return false}return true}
function cleanMessages(messages){if(!Array.isArray(messages))return[];return messages.filter(m=>m&&typeof m==="object"&&["user","assistant","model"].includes(m.role)&&typeof m.content==="string"&&m.content.trim()).map(m=>({role:m.role==="assistant"||m.role==="model"?"model":"user",content:m.content.trim().slice(0,MAX_MESSAGE_LENGTH)})).slice(-MAX_MESSAGES)}
function toGemini(messages){return messages.map(m=>({role:m.role,parts:[{text:m.content}]}))}
function textOf(r){if(typeof r?.text==="string"&&r.text.trim())return r.text.trim();const p=r?.candidates?.flatMap(c=>Array.isArray(c?.content?.parts)?c.content.parts:[])||[];return p.filter(x=>typeof x?.text==="string").map(x=>x.text).join("\n").trim()}
function chunkText(c){if(typeof c?.text==="string")return c.text;const p=c?.candidates?.flatMap(x=>Array.isArray(x?.content?.parts)?x.content.parts:[])||[];return p.filter(x=>typeof x?.text==="string").map(x=>x.text).join("")}
function groundingOf(r){const m=r?.candidates?.[0]?.groundingMetadata||r?.groundingMetadata||null;const chunks=Array.isArray(m?.groundingChunks)?m.groundingChunks:[];const sources=chunks.map((c,i)=>{const w=c?.web||c?.retrievedContext;return w?.uri?{index:i,title:w.title||new URL(w.uri).hostname,uri:w.uri}:null}).filter(Boolean);return{metadata:m,sources,supports:Array.isArray(m?.groundingSupports)?m.groundingSupports:[]}}
async function generate(options){let last=null;for(let i=0;i<FALLBACK_MODELS.length;i++){const model=FALLBACK_MODELS[i];try{return{response:await ai.models.generateContent({...options,model}),model}}catch(e){last=e;const s=statusOf(e);if(![408,425,429,500,502,503,504].includes(s))throw e;if(i<FALLBACK_MODELS.length-1)continue}}throw last||new Error("Aucun modèle Gemini disponible.")}
async function generateStream(options,res){let last=null;for(let i=0;i<FALLBACK_MODELS.length;i++){const model=FALLBACK_MODELS[i];try{const stream=await ai.models.generateContentStream({...options,model});res.write(`event: start\ndata: ${JSON.stringify({model})}\n\n`);let full="";for await(const chunk of stream){const text=chunkText(chunk);if(text){full+=text;res.write(`data: ${JSON.stringify({text})}\n\n`)}}if(!full.trim())throw new Error("Wiener IA n'a retourné aucune réponse.");res.write(`event: done\ndata: ${JSON.stringify({answer:full.trim(),model})}\n\n`);res.end();return}catch(e){last=e;const s=statusOf(e);if(res.headersSent)throw e;if(![408,425,429,500,502,503,504].includes(s))throw e;if(i<FALLBACK_MODELS.length-1)continue}}throw last||new Error("Aucun modèle Gemini disponible.")}
async function generateImage(prompt){let last=null;for(const model of [...new Set(IMAGE_MODELS)]){try{const x=await ai.interactions.create({model,input:prompt,response_format:{type:"image",mime_type:"image/jpeg",aspect_ratio:"1:1",image_size:"1K"}});const d=x?.output_image?.data;if(d)return{data:d,model};const b=x?.steps?.flatMap(s=>s?.type==="model_output"?(s.content||[]):[]).find(c=>c?.type==="image"&&c?.data);if(b)return{data:b.data,model};throw new Error("Le modèle image n'a fourni aucune image.")}catch(e){last=e;const s=statusOf(e);if(![408,425,429,500,502,503,504].includes(s))throw e}}throw last||new Error("Aucun modèle image disponible.")}
function sendError(res,e){console.error("Wiener IA:",e?.message||e);const s=statusOf(e);if(s===401||s===403)return res.status(s).json({error:"La clé Gemini est invalide ou non autorisée."});if(s===404)return res.status(404).json({error:"Le modèle Gemini demandé est indisponible."});if(s===429)return res.status(429).json({error:"Gemini est temporairement limité. Réessaie dans quelques instants."});if([502,503,504].includes(s))return res.status(s).json({error:"Le service Gemini est temporairement indisponible."});return res.status(500).json({error:e?.message||"Une erreur serveur est survenue."})}
app.get("/",(_,res)=>res.sendFile(path.join(__dirname,"index.html")));
app.get("/health",(_,res)=>res.json({ok:true,service:"Wiener IA",geminiConfigured:Boolean(ai),model:TEXT_MODEL}));
app.get("/api/health",(_,res)=>res.json({ok:true,service:"Wiener IA",geminiConfigured:Boolean(ai),textModel:TEXT_MODEL,time:new Date().toISOString()}));
app.post("/api/chat",async(req,res)=>{try{if(!requireAI(res))return;let messages=cleanMessages(req.body?.messages);if(!messages.length&&typeof req.body?.message==="string"&&req.body.message.trim())messages=[{role:"user",content:req.body.message.trim()}];if(!messages.length)return res.status(400).json({error:"Aucun message valide n'a été reçu."});res.setHeader("Content-Type","text/event-stream; charset=utf-8");res.setHeader("Cache-Control","no-cache, no-transform");res.setHeader("Connection","keep-alive");res.flushHeaders?.();await generateStream({contents:toGemini(messages),config:{systemInstruction:BASE_INSTRUCTIONS,maxOutputTokens:768,temperature:.3}},res)}catch(e){if(res.headersSent){res.write(`event: error\ndata: ${JSON.stringify({error:e?.message||"La réponse a été interrompue."})}\n\n`);res.end()}else sendError(res,e)}});
app.post("/api/exercises",async(req,res)=>{try{if(!requireAI(res))return;const q=typeof req.body?.question==="string"?req.body.question.trim():typeof req.body?.message==="string"?req.body.message.trim():"";if(!q)return res.status(400).json({error:"Aucun exercice n'a été reçu."});const r=await generate({contents:[{role:"user",parts:[{text:q}]}],config:{systemInstruction:EXERCISE_INSTRUCTIONS,maxOutputTokens:1536,temperature:.2}});const answer=textOf(r.response);if(!answer)return res.status(502).json({error:"Aucune solution n'a été retournée."});res.json({answer,model:r.model})}catch(e){sendError(res,e)}});
app.post("/api/calculate",(req,res)=>{const expression=typeof req.body?.expression==="string"?req.body.expression.trim():"";if(!expression)return res.status(400).json({error:"Expression vide."});if(expression.length>500||!/^[0-9+\-*/().,%\s^]+$/.test(expression))return res.status(400).json({error:"Expression non prise en charge."});try{const n=expression.replace(/,/g,".").replace(/\^/g,"**").replace(/%/g,"/100"),result=Function(`"use strict";return (${n})`)();if(!Number.isFinite(result))throw Error();res.json({result:String(result)})}catch{res.status(400).json({error:"Expression mathématique invalide."})}});
app.post("/api/search",async(req,res)=>{try{if(!requireAI(res))return;const query=typeof req.body?.query==="string"?req.body.query.trim():"";if(!query)return res.status(400).json({error:"Recherche vide."});const r=await generate({contents:query,config:{systemInstruction:SEARCH_INSTRUCTIONS,tools:[{googleSearch:{}}],maxOutputTokens:1536,temperature:.2}});const answer=textOf(r.response);if(!answer)return res.status(502).json({error:"Aucun résultat de recherche."});const g=groundingOf(r.response);res.json({answer,response:answer,model:r.model,search:true,groundingMetadata:g.metadata,sources:g.sources,supports:g.supports,queries:g.metadata?.webSearchQueries||g.metadata?.searchQueries||[]})}catch(e){sendError(res,e)}});
app.post("/api/image",async(req,res)=>{try{if(!requireAI(res))return;const prompt=typeof req.body?.prompt==="string"?req.body.prompt.trim():"";if(!prompt)return res.status(400).json({error:"Décris l'image à générer."});const r=await generateImage(prompt);res.json({ok:true,model:r.model,image:`data:image/jpeg;base64,${r.data}`})}catch(e){sendError(res,e)}});
app.post("/api/analyze-file",upload.single("file"),async(req,res)=>{try{if(!requireAI(res))return;if(!req.file)return res.status(400).json({error:"Aucun fichier reçu."});const mime=req.file.mimetype||"application/octet-stream",allowed=["application/pdf","image/png","image/jpeg","image/webp"];if(!allowed.includes(mime))return res.status(415).json({error:"Type de fichier non pris en charge."});const prompt=typeof req.body?.prompt==="string"&&req.body.prompt.trim()?req.body.prompt.trim():"Analyse ce fichier et réponds clairement à la demande.";const r=await generate({contents:[{role:"user",parts:[{text:prompt},{inlineData:{mimeType:mime,data:req.file.buffer.toString("base64")}}]}],config:{systemInstruction:BASE_INSTRUCTIONS,maxOutputTokens:2048,temperature:.2}});const answer=textOf(r.response);if(!answer)return res.status(502).json({error:"Aucune analyse n'a été retournée."});res.json({answer,model:r.model,file:{name:req.file.originalname,mimeType:mime,size:req.file.size}})}catch(e){sendError(res,e)}});
app.post("/api/consciousness",async(req,res)=>{try{if(!requireAI(res))return;const text=typeof req.body?.text==="string"?req.body.text.trim():"";if(!text)return res.status(400).json({error:"Texte manquant."});const r=await generate({contents:text,config:{systemInstruction:ANALYSIS_INSTRUCTIONS,maxOutputTokens:768,temperature:.2}});res.json({analysis:textOf(r.response),functional:true,model:r.model})}catch(e){sendError(res,e)}});
app.post("/api/analyze",async(req,res)=>{try{if(!requireAI(res))return;const text=typeof req.body?.text==="string"?req.body.text.trim():"";if(!text)return res.status(400).json({error:"Texte à analyser manquant."});const r=await generate({contents:text,config:{systemInstruction:ANALYSIS_INSTRUCTIONS,maxOutputTokens:768,temperature:.2}});res.json({analysis:textOf(r.response),functional:true,model:r.model})}catch(e){sendError(res,e)}});
app.use((err,req,res,next)=>{if(err?.code==="LIMIT_FILE_SIZE")return res.status(413).json({error:"Fichier trop volumineux. Taille maximale : 20 MB."});next(err)});
app.listen(PORT,"0.0.0.0",()=>console.log(`Wiener IA démarré sur 0.0.0.0:${PORT}`));
