import React,{useEffect,useRef,useState} from 'react';
import {ActivityIndicator,Alert,FlatList,KeyboardAvoidingView,Platform,Pressable,SafeAreaView,StyleSheet,Text,TextInput,View} from 'react-native';
import {NavigationContainer} from '@react-navigation/native';
import {createBottomTabNavigator} from '@react-navigation/bottom-tabs';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {Ionicons} from '@expo/vector-icons';
import {StatusBar} from 'expo-status-bar';

const API='https://wiener-ia.onrender.com';
const Tab=createBottomTabNavigator();
const HISTORY_KEY='wiener_mobile_chat_v1';

function Header({title,subtitle}){return <View style={styles.header}><View style={styles.logo}><Text style={styles.logoText}>W</Text></View><View><Text style={styles.headerTitle}>{title}</Text>{subtitle?<Text style={styles.headerSub}>{subtitle}</Text>:null}</View></View>}

function ChatScreen(){
 const [messages,setMessages]=useState([]); const [input,setInput]=useState(''); const [busy,setBusy]=useState(false); const [online,setOnline]=useState(false); const list=useRef(null);
 useEffect(()=>{(async()=>{try{const raw=await AsyncStorage.getItem(HISTORY_KEY);if(raw)setMessages(JSON.parse(raw))}catch{}})(); fetch(API+'/api/health',{cache:'no-store'}).then(r=>setOnline(r.ok)).catch(()=>setOnline(false))},[]);
 useEffect(()=>{AsyncStorage.setItem(HISTORY_KEY,JSON.stringify(messages.slice(-80))).catch(()=>{})},[messages]);
 const send=async()=>{const text=input.trim();if(!text||busy)return;setInput('');const user={id:Date.now().toString(),role:'user',content:text};const next=[...messages,user];setMessages(next);setBusy(true);try{const r=await fetch(API+'/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:next.slice(-8)})});if(!r.ok){let d={};try{d=await r.json()}catch{}throw Error(d.error||'Le serveur Wiener IA ne répond pas.')}if(!r.body)throw Error('Le streaming n’est pas disponible.');const reader=r.body.getReader(),decoder=new TextDecoder();let buffer='',answer='';const assistantId=(Date.now()+1).toString();setMessages(v=>[...v,{id:assistantId,role:'model',content:''}]);while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const chunks=buffer.split('\n\n');buffer=chunks.pop()||'';for(const chunk of chunks){for(const line of chunk.split('\n')){if(!line.startsWith('data:'))continue;let x;try{x=JSON.parse(line.slice(5).trim())}catch{continue}if(x.error)throw Error(x.error);if(x.text){answer+=x.text;setMessages(v=>v.map(m=>m.id===assistantId?{...m,content:answer}:m))}}}}if(!answer)throw Error('Wiener IA n’a retourné aucune réponse.')}catch(e){setMessages(v=>[...v,{id:(Date.now()+2).toString(),role:'model',content:'⚠️ '+e.message}])}finally{setBusy(false)}};
 return <SafeAreaView style={styles.screen}><StatusBar style="light"/><Header title="Wiener IA" subtitle={online?'En ligne':'Connexion en cours…'}/><FlatList ref={list} data={messages} keyExtractor={x=>x.id} contentContainerStyle={styles.list} onContentSizeChange={()=>list.current?.scrollToEnd({animated:true})} ListEmptyComponent={<View style={styles.welcome}><View style={styles.bigLogo}><Text style={styles.bigLogoText}>W</Text></View><Text style={styles.welcomeTitle}>Bonjour, je suis Wiener IA</Text><Text style={styles.welcomeText}>Pose-moi une question, demande une explication ou aide-toi de mes outils.</Text></View>} renderItem={({item})=><View style={[styles.message,item.role==='user'?styles.user:styles.assistant]}><Text style={styles.messageText}>{item.content||'…'}</Text></View>}/><KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined}><View style={styles.composer}><TextInput value={input} onChangeText={setInput} placeholder="Écrivez un message…" placeholderTextColor="#777" multiline style={styles.input} onSubmitEditing={e=>{if(Platform.OS!=='ios')send()}}/><Pressable onPress={send} disabled={busy||!input.trim()} style={[styles.send,!input.trim()||busy?styles.disabled:null]}><Ionicons name="arrow-up" size={21} color="#111"/></Pressable></View></KeyboardAvoidingView></SafeAreaView>
}

function ToolsScreen(){return <SafeAreaView style={styles.screen}><StatusBar style="light"/><Header title="Outils" subtitle="Wiener IA"/><View style={styles.tools}><Tool icon="search" title="Recherche Web" text="Rechercher des informations actuelles avec Google."/><Tool icon="school" title="Exercices" text="Résoudre et expliquer des exercices étape par étape."/><Tool icon="image" title="Génération d’images" text="Créer une image à partir d’une description."/><Tool icon="document-text" title="Analyse de fichiers" text="Analyser PDF et images avec Wiener IA."/></View></SafeAreaView>}
function Tool({icon,title,text}){return <View style={styles.tool}><View style={styles.toolIcon}><Ionicons name={icon} size={22} color="#fff"/></View><View style={{flex:1}}><Text style={styles.toolTitle}>{title}</Text><Text style={styles.toolText}>{text}</Text></View></View>}

function HistoryScreen(){const [messages,setMessages]=useState([]);useEffect(()=>{AsyncStorage.getItem(HISTORY_KEY).then(x=>x&&setMessages(JSON.parse(x))).catch(()=>{})},[]);return <SafeAreaView style={styles.screen}><StatusBar style="light"/><Header title="Historique" subtitle="Vos conversations sur cet appareil"/><FlatList data={messages.filter(x=>x.role==='user').reverse()} keyExtractor={x=>x.id} contentContainerStyle={styles.history} ListEmptyComponent={<Text style={styles.empty}>Aucune conversation enregistrée.</Text>} renderItem={({item})=><View style={styles.historyRow}><Ionicons name="chatbubble-outline" size={20} color="#aaa"/><Text numberOfLines={2} style={styles.historyText}>{item.content}</Text></View>}/></SafeAreaView>}

function SettingsScreen(){return <SafeAreaView style={styles.screen}><StatusBar style="light"/><Header title="Paramètres" subtitle="Wiener IA"/><View style={styles.settings}><Text style={styles.section}>APPLICATION</Text><View style={styles.settingRow}><Ionicons name="cloud-outline" size={21} color="#aaa"/><View><Text style={styles.settingTitle}>Serveur</Text><Text style={styles.settingText}>{API}</Text></View></View><View style={styles.settingRow}><Ionicons name="shield-checkmark-outline" size={21} color="#aaa"/><View><Text style={styles.settingTitle}>Données</Text><Text style={styles.settingText}>L’historique local reste sur cet appareil.</Text></View></View><Pressable style={styles.clear} onPress={()=>Alert.alert('Effacer l’historique','Supprimer les conversations locales ?', [{text:'Annuler',style:'cancel'},{text:'Effacer',style:'destructive',onPress:()=>AsyncStorage.removeItem(HISTORY_KEY)}])}><Ionicons name="trash-outline" size={20} color="#fff"/><Text style={styles.clearText}>Effacer l’historique</Text></Pressable></View></SafeAreaView>}

export default function App(){return <NavigationContainer><Tab.Navigator screenOptions={({route})=>({headerShown:false,tabBarStyle:styles.tab,tabBarActiveTintColor:'#fff',tabBarInactiveTintColor:'#777',tabBarLabelStyle:{fontSize:10},tabBarIcon:({color,size})=>{const icons={Chat:'chatbubble',Outils:'grid',Historique:'time',Paramètres:'settings'};return <Ionicons name={icons[route.name]||'ellipse'} size={size} color={color}/>}})}><Tab.Screen name="Chat" component={ChatScreen}/><Tab.Screen name="Outils" component={ToolsScreen}/><Tab.Screen name="Historique" component={HistoryScreen}/><Tab.Screen name="Paramètres" component={SettingsScreen}/></Tab.Navigator></NavigationContainer>}

const styles=StyleSheet.create({screen:{flex:1,backgroundColor:'#171717'},header:{height:72,paddingHorizontal:18,flexDirection:'row',alignItems:'center',borderBottomWidth:1,borderBottomColor:'#303030',gap:11},logo:{width:40,height:40,borderRadius:12,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},logoText:{fontSize:22,fontWeight:'900',color:'#111'},headerTitle:{fontSize:18,fontWeight:'800',color:'#fff'},headerSub:{fontSize:11,color:'#777',marginTop:2},list:{padding:16,paddingBottom:18,flexGrow:1},welcome:{flex:1,justifyContent:'center',alignItems:'center',paddingHorizontal:28},bigLogo:{width:66,height:66,borderRadius:19,backgroundColor:'#fff',alignItems:'center',justifyContent:'center',marginBottom:18},bigLogoText:{fontSize:34,fontWeight:'900',color:'#111'},welcomeTitle:{fontSize:23,fontWeight:'800',color:'#fff',textAlign:'center'},welcomeText:{fontSize:14,color:'#888',textAlign:'center',lineHeight:21,marginTop:8},message:{maxWidth:'88%',padding:12,borderRadius:16,marginVertical:6},user:{alignSelf:'flex-end',backgroundColor:'#303030'},assistant:{alignSelf:'flex-start',backgroundColor:'transparent',paddingHorizontal:2},messageText:{color:'#eee',fontSize:15,lineHeight:22},composer:{margin:8,padding:6,minHeight:54,maxHeight:150,borderWidth:1,borderColor:'#3d3d3d',borderRadius:16,backgroundColor:'#292929',flexDirection:'row',alignItems:'flex-end'},input:{flex:1,color:'#fff,fontSize:15,paddingHorizontal:10,paddingVertical:9,maxHeight:125},send:{width:40,height:40,borderRadius:12,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},disabled:{opacity:.35},tab:{height:63,paddingTop:5,paddingBottom:5,backgroundColor:'#202020',borderTopColor:'#333'},tools:{padding:16,gap:10},tool:{backgroundColor:'#202020',borderWidth:1,borderColor:'#333',borderRadius:14,padding:15,flexDirection:'row',alignItems:'center',gap:13},toolIcon:{width:42,height:42,borderRadius:12,backgroundColor:'#303030',alignItems:'center',justifyContent:'center'},toolTitle:{color:'#fff',fontSize:15,fontWeight:'750'},toolText:{color:'#888',fontSize:12,marginTop:3},history:{padding:14},historyRow:{flexDirection:'row',alignItems:'center',gap:12,padding:14,borderBottomWidth:1,borderBottomColor:'#292929'},historyText:{flex:1,color:'#ddd',fontSize:14},empty:{color:'#777',textAlign:'center',marginTop:60},settings:{padding:18},section:{fontSize:11,color:'#777',letterSpacing:1,marginBottom:10},settingRow:{flexDirection:'row',gap:13,paddingVertical:15,borderBottomWidth:1,borderBottomColor:'#292929'},settingTitle:{color:'#eee',fontSize:14,fontWeight:'700'},settingText:{color:'#777',fontSize:11,marginTop:3,maxWidth:300},clear:{marginTop:30,borderWidth:1,borderColor:'#444',borderRadius:12,padding:13,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},clearText:{color:'#fff',fontWeight:'700'}});
